### ISSUE TITLE
Wie kann ich die Libs bekommen / Instalieren für c++?

### ISSUE THREAD

**Issue by MorrisBrProjects** [tlmrgvf/drtd#9]
┌──(kali㉿kali-rpi0w)-[~/drtd/build]
└─$ sudo cmake ..
-- Could NOT find OpenGL (missing: OPENGL_opengl_LIBRARY OPENGL_glx_LIBRARY OPENGL_INCLUDE_DIR)
-- Could NOT find X11 (missing: X11_X11_INCLUDE_PATH X11_X11_LIB)
CMake Error at /usr/share/cmake-3.22/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find FLTK (missing: FLTK_LIBRARIES FLTK_INCLUDE_DIR
  FLTK_FLUID_EXECUTABLE)
Call Stack (most recent call first):
  /usr/share/cmake-3.22/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.22/Modules/FindFLTK.cmake:329 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:31 (find_package)

-- Configuring incomplete, errors occurred!
See also "/home/kali/drtd/build/CMakeFiles/CMakeOutput.log".

**Comment by tlmrgvf** [comment]
To install the required libraries (as listed in the README), you should be able to use your distributions package manager.
Under e.g. Ubuntu this would be something like
`$ sudo apt install fltk1.3-dev`
to install fltk.
